import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';
import {api,seal} from '../server/app.mjs';
test('spoken followup streams speech before the complete answer and returns signed history',async()=>{const secret='interrupt-test';const context=await seal({query:'蓝天',references:[],status:[],script:[{text:'阳光发生散射。'}]},secret,'local-preview');let speechCalls=0;const response=await api(new Request('https://test/api/followup',{method:'POST',body:JSON.stringify({context,query:'举个例子',chapter:0,voiceReply:true})}),{LOCAL_DEV:true,ZHIHU_ACCESS_SECRET:secret,VOLC_API_KEY:'test',FETCH:async()=>new Response('data: '+JSON.stringify({choices:[{delta:{content:'可以想象阳光照进空气里的微小颗粒。'}}]})+'\n\ndata: '+JSON.stringify({choices:[{delta:{content:'不同颜色的光会向不同方向散开。'}}]})+'\n\ndata: [DONE]\n',{headers:{'Content-Type':'text/event-stream'}}),VOICE_FETCH:async()=>{speechCalls++;return new Response('{"code":0,"data":"YWJj"}\n{"code":20000000}\n')}});const events=(await response.text()).split('\n').filter(s=>s.startsWith('data:')).map(s=>JSON.parse(s.slice(5)));assert.equal(response.status,200);assert.equal(speechCalls,2);assert.equal(events.filter(e=>e.type==='speech-end').length,2);assert.ok(events.findIndex(e=>e.type==='audio')<events.findLastIndex(e=>e.type==='token'));assert.ok(events.find(e=>e.type==='result').result.context);assert.equal(events.at(-1).type,'complete')});
function ui(){const elements=new Map();const element=()=>({textContent:'',innerHTML:'',hidden:false,className:'',classList:{add(){},remove(){}},append(){},setAttribute(k,v){this[k]=v}});let sockets=[],tracksStopped=0,fallbacks=0,resumes=0;const document={getElementById(id){if(!elements.has(id))elements.set(id,element());return elements.get(id)},createElement:element,querySelectorAll(){return []},addEventListener(){}};class WS{constructor(){this.readyState=0;this.bufferedAmount=0;this.sent=[];sockets.push(this)}open(){this.readyState=1;this.onopen?.()}send(value){this.sent.push(value)}close(){this.readyState=3;this.onclose?.()}message(data){this.onmessage?.({data:JSON.stringify(data)})}}class AC{constructor(){this.state='running';this.sampleRate=16000;this.currentTime=0;this.destination={}}async resume(){}async decodeAudioData(){return {duration:.01}}createBufferSource(){return {connect(){},start(){},stop(){},disconnect(){}}}createBuffer(_channels,length,rate){const data=new Float32Array(length);return {duration:length/rate,getChannelData(){return data}}}createMediaStreamSource(){return {connect(){},disconnect(){}}}createScriptProcessor(){this.processor={connect(){},disconnect(){}};return this.processor}}
const context=vm.createContext({document,window:{AudioContext:AC,addEventListener(){}},navigator:{mediaDevices:{getUserMedia:async()=>({getTracks:()=>[{stop(){tracksStopped++}}]})}},location:{origin:'https://test'},WebSocket:WS,AbortController,Uint8Array,Int16Array,Float32Array,setTimeout,clearTimeout,setInterval,clearInterval,Blob,atob,state:{episode:{context:'signed',engine:'tts',segments:[{sourceIndex:0,text:'阳光发生散射。'}]},index:0,playing:true,paused:false,page:'player',rate:1,voice:'female'},episodeAudio:null,followAnswer:null,render(){},toast(){},pauseCloudAudio(){},playCloudSegment(){resumes++},readVoiceStream:async()=>{fallbacks++}});vm.runInContext(fs.readFileSync('public/interrupt.js','utf8'),context);return {context,sockets,get tracksStopped(){return tracksStopped},get fallbacks(){return fallbacks},get resumes(){return resumes}}}
test('hold streams PCM only after ready, commits on release and stops the microphone',async()=>{const x=ui();vm.runInContext("state.followContext='another-episode-context'",x.context);await vm.runInContext('beginInterrupt()',x.context);const ws=x.sockets[0];ws.open();assert.equal(JSON.parse(ws.sent[0]).type,'start');assert.equal(JSON.parse(ws.sent[0]).context,'signed');ws.message({type:'ready'});vm.runInContext('interruption.pending=new Uint8Array(640);interruption.allPcm=[new Uint8Array(12800)];interruption.recordedBytes=12800',x.context);vm.runInContext('pumpPcm(interruption)',x.context);assert.ok(ws.sent[1] instanceof ArrayBuffer);vm.runInContext('releaseInterrupt(false);pumpPcm(interruption)',x.context);assert.ok(x.tracksStopped>0);assert.equal(JSON.parse(ws.sent.at(-1)).type,'commit');assert.equal(x.fallbacks,0);vm.runInContext('stopInterrupt()',x.context)});
test('release before duplex ready hides the overlay and commits as soon as ready arrives',async()=>{const x=ui();await vm.runInContext('beginInterrupt()',x.context);const ws=x.sockets[0];ws.open();vm.runInContext('interruption.pending=new Uint8Array(12800);interruption.allPcm=[new Uint8Array(12800)];interruption.recordedBytes=12800;releaseInterrupt(false)',x.context);assert.equal(vm.runInContext('interruption.phase',x.context),'recognizing');assert.notEqual(x.context.document.getElementById('interrupt-panel').hidden,false);ws.message({type:'ready'});assert.equal(vm.runInContext('interruption.phase',x.context),'recognizing');assert.ok(ws.sent.some(value=>value instanceof ArrayBuffer));vm.runInContext('pumpPcm(interruption);pumpPcm(interruption)',x.context);assert.equal(JSON.parse(ws.sent.at(-1)).type,'commit');assert.equal(ws.sent.filter(v=>v instanceof ArrayBuffer).length,20);assert.equal(x.fallbacks,0);vm.runInContext('stopInterrupt()',x.context)});
test('slide cancel closes the full-duplex turn without submitting fallback',async()=>{const x=ui();await vm.runInContext('beginInterrupt()',x.context);const ws=x.sockets[0];ws.open();ws.message({type:'ready'});vm.runInContext('interruption.allPcm=[new Uint8Array(640)];releaseInterrupt(true)',x.context);assert.equal(x.fallbacks,0);assert.equal(ws.readyState,3);assert.equal(vm.runInContext('interruption',x.context),null)});
test('another press cancels stale audio and preserves the original resume intent',async()=>{const x=ui();await vm.runInContext('beginInterrupt()',x.context);const signal=vm.runInContext('interruption.abort.signal',x.context);await vm.runInContext('beginInterrupt()',x.context);assert.equal(signal.aborted,true);assert.equal(vm.runInContext('interruption.resumeAfter',x.context),true);vm.runInContext('stopInterrupt(true)',x.context);assert.equal(x.resumes,1);assert.equal(vm.runInContext('interruption',x.context),null)});
test('completed conversation resumes from the paused program position',async()=>{const x=ui();await vm.runInContext('beginInterrupt()',x.context);vm.runInContext("interruption.released=true;interruption.boundaryReached=true;interruption.result={context:'new'};interruption.audioDone=true;scheduleConversationFinish(interruption)",x.context);await new Promise(r=>setTimeout(r,100));assert.equal(x.resumes,1);assert.equal(vm.runInContext('state.followContext',x.context),'new');assert.equal(vm.runInContext('state.index',x.context),0)});

test('a short accidental press is discarded and the program resumes',async()=>{const x=ui();await vm.runInContext('beginInterrupt()',x.context);vm.runInContext('interruption.allPcm=[new Uint8Array(1000)];interruption.recordedBytes=1000;releaseInterrupt(false)',x.context);assert.equal(vm.runInContext('interruption',x.context),null);assert.equal(x.resumes,1)});

test('release during a pending microphone permission discards late media and opens no socket',async()=>{const x=ui();let grant,stopped=0;x.context.navigator.mediaDevices.getUserMedia=()=>new Promise(resolve=>grant=resolve);const pending=vm.runInContext('beginInterrupt()',x.context);await new Promise(r=>setImmediate(r));vm.runInContext('releaseInterrupt(true)',x.context);grant({getTracks:()=>[{stop(){stopped++}}]});await pending;assert.equal(stopped,1);assert.equal(x.sockets.length,0);assert.equal(vm.runInContext('interruption',x.context),null)});

test('microphone opening timeout cancels turn and late permission cannot resurrect it',async()=>{const x=ui();let timeout,grant;x.context.setTimeout=(fn,ms)=>{if(ms===12000){timeout=fn;return 0}return setTimeout(fn,ms)};x.context.navigator.mediaDevices.getUserMedia=()=>new Promise(resolve=>grant=resolve);const pending=vm.runInContext('beginInterrupt()',x.context);await new Promise(r=>setImmediate(r));timeout();assert.equal(vm.runInContext('interruption',x.context),null);grant({getTracks:()=>[{stop(){}}]});await pending;assert.equal(x.sockets.length,0);assert.equal(x.resumes,1)});

test('pressing to interrupt pauses immediately and restarts the interrupted sentence',async()=>{const x=ui();vm.runInContext("state.episode.segments[0].text='这一句还在播放。';episodeAudio={volume:1,currentTime:6,duration:10,paused:false,ended:false,pause(){this.paused=true},onended(){state.index=99}};const audio=episodeAudio;interruption={episode:state.episode,audioIndex:0,programAudio:audio,resumeAfter:true,abort:new AbortController(),sources:new Set(),audioQueue:[],audioDone:false};globalThis.done=sentenceBoundary(interruption);audio.onended()",x.context);await vm.runInContext('done',x.context);assert.equal(vm.runInContext('episodeAudio.paused',x.context),true);assert.equal(vm.runInContext('state.index',x.context),0);assert.equal(vm.runInContext('interruption.resumeTime',x.context),0);vm.runInContext('stopInterrupt(true)',x.context);assert.equal(vm.runInContext('state.index',x.context),0);assert.equal(x.resumes,1)});

test('server bridge creates a duplex session, forwards PCM and returns streamed audio context',async()=>{class Socket extends EventTarget{constructor(){super();this.sent=[];this.readyState=1}send(value){this.sent.push(value)}close(){if(this.readyState===3)return;this.readyState=3;this.dispatchEvent(new Event('close'))}message(data){this.dispatchEvent(new MessageEvent('message',{data:typeof data==='string'?data:JSON.stringify(data)}))}}const browser=new Socket(),upstream=new Socket(),secret='duplex-test',tick=()=>new Promise(r=>setTimeout(r,5));try{const context=await seal({query:'蓝天',references:[],status:[],script:[{text:'阳光发生散射。'}]},secret,'local-preview');const response=await api(new Request('https://test/api/voice/duplex',{headers:{upgrade:'websocket'}}),{LOCAL_DEV:true,ZHIHU_ACCESS_SECRET:secret,VOLC_API_KEY:'test',DUPLEX_UPGRADE:attach=>{attach(browser);return new Response(null)},VOICE_CONNECT:async()=>upstream});assert.equal(response.status,200);browser.message({type:'start',context,chapter:0,voice:'female'});await tick();const created=JSON.parse(upstream.sent[0]);assert.equal(created.type,'session.create');assert.equal(created.session.audio.output.format.type,'pcm_s16le');assert.equal(created.session.audio.input.format.type,'pcm');assert.ok(created.extension?.asr);assert.equal(created.session.extension,undefined);upstream.message({type:'session.created'});await tick();assert.equal(JSON.parse(browser.sent.at(-1)).type,'ready');browser.dispatchEvent(new MessageEvent('message',{data:new Uint8Array(640)}));await tick();assert.equal(JSON.parse(upstream.sent.at(-1)).type,'input_audio_buffer.append');browser.message({type:'commit'});await tick();assert.equal(JSON.parse(upstream.sent.at(-2)).type,'input_audio_buffer.commit');assert.equal(JSON.parse(upstream.sent.at(-1)).type,'input_audio_mute.commit');upstream.message({type:'response.output_audio.delta',delta:'YWI='});upstream.message({type:'response.output_audio.done'});upstream.message({type:'response.output_text.delta',delta:'刚才你问到蓝天。'});upstream.message({type:'response.done'});for(let attempt=0;attempt<200&&!browser.sent.some(x=>JSON.parse(x).type==='result');attempt++)await tick();const messages=browser.sent.map(x=>JSON.parse(x));assert.equal(messages.find(x=>x.type==='audio').data,'YWI=');assert.ok(messages.find(x=>x.type==='result').result.context);browser.message({type:'cancel'});await tick();assert.equal(JSON.parse(upstream.sent.at(-1)).type,'response.cancel')}finally{browser.message({type:'close'});browser.close();upstream.close()}});

test('duplex male voice uses verified Yunzhou and empty audio cannot complete successfully',async()=>{
 class Socket extends EventTarget{constructor(){super();this.sent=[];this.readyState=1}send(value){this.sent.push(JSON.parse(value))}close(){if(this.readyState===3)return;this.readyState=3;this.dispatchEvent(new Event('close'))}message(data){this.dispatchEvent(new MessageEvent('message',{data:JSON.stringify(data)}))}}
 const browser=new Socket(),upstream=new Socket(),secret='empty-duplex',tick=()=>new Promise(r=>setTimeout(r,5));
 try{const context=await seal({query:'蓝天',references:[],status:[],script:[{text:'光的散射'}]},secret,'local-preview');await api(new Request('https://test/api/voice/duplex',{headers:{upgrade:'websocket'}}),{LOCAL_DEV:true,ZHIHU_ACCESS_SECRET:secret,VOLC_API_KEY:'test',DUPLEX_UPGRADE:attach=>{attach(browser);return new Response(null)},VOICE_CONNECT:async()=>upstream});browser.message({type:'start',context,voice:'male'});await tick();assert.equal(upstream.sent[0].session.audio.output.voice,'zh_male_yunzhou_jupiter_bigtts');upstream.message({type:'session.created'});upstream.message({type:'response.output_audio.done'});upstream.message({type:'response.done'});await tick();assert.equal(browser.sent.find(m=>m.type==='error')?.code,'DUPLEX_EMPTY_AUDIO');assert.equal(browser.sent.some(m=>m.type==='result'),false)}finally{browser.close();upstream.close()}
});
test('duplex gender follows the selected voice instead of assuming speaker B is male',()=>{const x=ui();assert.equal(vm.runInContext("duplexSpeakerFor({duoVoices:['zh_male_liufei_uranus_bigtts','zh_female_vv_uranus_bigtts'],segments:[{speaker:'A'},{speaker:'B'}]},0)",x.context),'male');assert.equal(vm.runInContext("duplexSpeakerFor({duoVoices:['zh_male_liufei_uranus_bigtts','zh_female_vv_uranus_bigtts'],segments:[{speaker:'A'},{speaker:'B'}]},1)",x.context),'female')});
test('recognition and retrieval milestones update visible waiting feedback',async()=>{const x=ui();try{await vm.runInContext('beginInterrupt()',x.context);const ws=x.sockets[0];ws.open();ws.message({type:'ready'});vm.runInContext('interruption.recordedBytes=12800;releaseInterrupt(false)',x.context);ws.message({type:'transcript',text:'为什么？',final:true});assert.match(x.context.document.getElementById('interrupt-listen-connection').textContent,/准备回答/);ws.message({type:'tool-start'});assert.match(x.context.document.getElementById('interrupt-listen-connection').textContent,/查找/)}finally{vm.runInContext('stopInterrupt()',x.context)}});
