import test from 'node:test';import assert from 'node:assert/strict';
import {splitVoiceSegments,voiceFrame,voiceDecode,ttsAudio,episodeVoice,podcastAudio,duplexSocket,VOICES} from '../server/voice.mjs';
import {api,seal} from '../server/app.mjs';

test('voice decoder handles Worker Blob messages and offset binary views',async()=>{const frame=voiceFrame(360,{text:'这是完整的响应'},'session');const padded=new Uint8Array(frame.length+10);padded.set(frame,5);for(const raw of [new Blob([frame]),new DataView(padded.buffer,5,frame.length),frame.buffer]){const d=await voiceDecode(raw);assert.equal(d.data.text,'这是完整的响应')}await assert.rejects(voiceDecode(new Blob([frame.slice(0,3)])),/语音响应不完整/)});
test('long spoken paragraphs split without losing citations or source index',()=>{const rows=splitVoiceSegments([{text:'知识。'.repeat(250)+'[S1]',speaker:'B',sourceIds:['S1']}]);assert.ok(rows.every(s=>s.text.length<=280));assert.equal(rows.map(x=>x.text).join(''),'知识。'.repeat(250));assert.ok(rows.every(s=>s.sourceIndex===0&&s.sourceIds[0]==='S1'));assert.throws(()=>splitVoiceSegments([{text:'知'.repeat(10001)}]))});
test('spoken paragraphs become sentence-level audio segments for exact interruption resume',()=>{const rows=splitVoiceSegments([{text:'第一句。第二句！最后一句没有句号',speaker:'A',sourceIds:['S1']}]);assert.deepEqual(rows.map(x=>x.text),['第一句。','第二句！','最后一句没有句号']);assert.ok(rows.every(s=>s.sourceIndex===0&&s.sourceIds[0]==='S1'))});
test('podcast binary session frames retain Unicode content',async()=>{const frame=voiceFrame(360,{text:'天空为什么蓝',speaker:'A'},'session');const d=await voiceDecode(frame);assert.equal(d.event,360);assert.equal(d.data.text,'天空为什么蓝');await assert.rejects(voiceDecode(frame.slice(0,-2)))});
test('TTS parses fragmented chunks and excludes incomplete audio success',async()=>{const enc=new TextEncoder(),response='{"code":0,"data":"YWJj"}\n{"code":20000000,"usage":{"text_words":2}}\n';const env={VOLC_API_KEY:'test',VOICE_FETCH:async(_url,init)=>{assert.equal(init.headers['X-Api-Key'],'test');return new Response(new ReadableStream({start(c){c.enqueue(enc.encode(response.slice(0,9)));c.enqueue(enc.encode(response.slice(9)));c.close()}}))}};const out=[];for await(const e of ttsAudio(env,'你好','',new AbortController().signal))out.push(e);assert.equal(out[0].data,'YWJj');assert.equal(out[1].usage.text_words,2);await assert.rejects(async()=>{for await(const e of ttsAudio({...env,VOICE_FETCH:async()=>new Response('{"code":0,"data":"YWJj"}\n')},'你好',''))void e})});
test('voice endpoint requires signed script and never accepts arbitrary client speech',async()=>{const env={LOCAL_DEV:true,ZHIHU_ACCESS_SECRET:'test',VOLC_API_KEY:'test'};let r=await api(new Request('https://test/api/voice/episode',{method:'POST',body:JSON.stringify({context:'bad',text:'arbitrary'})}),env);assert.equal(r.status,400);const context=await seal({answer:'hi'},'test','local-preview');r=await api(new Request('https://test/api/voice/episode',{method:'POST',body:JSON.stringify({context})}),env);assert.equal(r.status,400);r=await api(new Request('https://test/api/voice/asr',{headers:{origin:'https://foreign',upgrade:'websocket'}}),env);assert.equal(r.status,403)});
test('podcast signals input completion after session starts so the server can finish',async()=>{const sent=[];class Socket extends EventTarget{send(raw){const event=new DataView(raw.buffer).getUint32(4);sent.push(event);queueMicrotask(()=>this.dispatchEvent(new MessageEvent('message',{data:voiceFrame(event===100?150:152,{},'test-session')})))}close(){}}const env={VOLC_API_KEY:'test',VOICE_CONNECT:async()=>new Socket()};for await(const e of podcastAudio(env,[{speaker:'A',text:'你好'}],AbortSignal.timeout(1000)))void e;assert.deepEqual(sent,[100,102])});
test('Worker duplex connection uses an HTTPS upgrade request',async()=>{const original=globalThis.fetch,accepted=[];try{globalThis.fetch=async(url,init)=>{assert.equal(url,'https://openspeech.bytedance.com/api/v3/duplex/realtime/dialogue');assert.equal(init.headers.Upgrade,'websocket');assert.equal(init.headers['X-Api-Key'],'test');return {webSocket:{accept(){accepted.push(true)}}}};await duplexSocket({VOLC_API_KEY:'test'});assert.equal(accepted.length,1)}finally{globalThis.fetch=original}});
test('duplex upstream is connected before the browser upgrade completes',async()=>{class Socket extends EventTarget{send(){}close(){this.dispatchEvent(new Event('close'))}}const browser=new Socket(),upstream=new Socket(),order=[];try{const response=await api(new Request('https://test/api/voice/duplex',{headers:{upgrade:'websocket'}}),{LOCAL_DEV:true,ZHIHU_ACCESS_SECRET:'test',VOLC_API_KEY:'test',VOICE_CONNECT:async()=>{order.push('upstream');return upstream},DUPLEX_UPGRADE:attach=>{order.push('browser');attach(browser);return new Response(null)}});assert.equal(response.status,200);assert.deepEqual(order,['upstream','browser'])}finally{browser.close();upstream.close()}});
