import {clapperAudio} from './clapper.mjs';
const voiceEncoder=new TextEncoder(),voiceDecoder=new TextDecoder();
export const VOICES=[
 {id:'zh_female_sophie_uranus_bigtts',name:'Sophie · 女声'},
 {id:'zh_male_liufei_uranus_bigtts',name:'刘飞 · 男声'},
 {id:'zh_male_dayi_uranus_bigtts',name:'大衣 · 男声'}
];
const podcastVoices=['zh_female_sophie_uranus_bigtts','zh_male_liufei_uranus_bigtts'];
export function voiceError(message,status=502){return Object.assign(new Error(message),{status,code:'VOICE_ERROR'})}
export function spokenText(text){return String(text||'').replace(/\[S\d+\]/g,'').replace(/[*#`]/g,'').trim()}
function voiceHeaders(env,resource){if(!env.VOLC_API_KEY)throw voiceError('语音服务尚未配置',503);return {'X-Api-Key':env.VOLC_API_KEY,'X-Api-Resource-Id':resource,'X-Api-Request-Id':crypto.randomUUID()}}
export function voiceFrame(event,payload,session){const body=voiceEncoder.encode(JSON.stringify(payload)),sid=session?voiceEncoder.encode(session):null;const out=new Uint8Array(4+4+(sid?4+sid.length:0)+4+body.length),v=new DataView(out.buffer);out.set([0x11,0x14,0x10,0]);let p=4;v.setUint32(p,event);p+=4;if(sid){v.setUint32(p,sid.length);p+=4;out.set(sid,p);p+=sid.length}v.setUint32(p,body.length);out.set(body,p+4);return out}
export async function voiceDecode(raw){if(raw instanceof Blob)raw=await raw.arrayBuffer();const a=ArrayBuffer.isView(raw)?new Uint8Array(raw.buffer,raw.byteOffset,raw.byteLength):new Uint8Array(raw),v=new DataView(a.buffer,a.byteOffset,a.byteLength);if(a.length<8)throw voiceError('语音响应不完整');const type=a[1]>>4,flags=a[1]&15;let p=(a[0]&15)*4,event=0,sequence,code;
 if(type===15){code=v.getUint32(p);p+=4}else{if(flags&1){sequence=v.getInt32(p);p+=4}if(flags&4){event=v.getUint32(p);p+=4;if(event>=100){const n=v.getUint32(p);p+=4+n}else if([50,51,52].includes(event)){const n=v.getUint32(p);p+=4+n}}}
 const size=v.getUint32(p);p+=4;if(size>a.length-p)throw voiceError('语音响应长度无效');let body=a.slice(p,p+size);if((a[2]&15)===1)body=new Uint8Array(await new Response(new Blob([body]).stream().pipeThrough(new DecompressionStream('gzip'))).arrayBuffer());let data=null;if((a[2]>>4)===1){try{data=JSON.parse(voiceDecoder.decode(body))}catch{throw voiceError('语音返回格式无效')}}return {type,event,sequence,code,body,data,last:!!(flags&2)};
}
export async function voiceSocket(env,path,resource){const headers=voiceHeaders(env,resource);if(env.VOICE_CONNECT)return env.VOICE_CONNECT('wss://openspeech.bytedance.com'+path,headers);const r=await fetch('https://openspeech.bytedance.com'+path,{headers:{...headers,Upgrade:'websocket'}});if(!r.webSocket)throw voiceError(r.status===401||r.status===403?'语音鉴权失败，请检查密钥及对应服务权限':'语音连接失败，请检查服务开通状态');const ws=r.webSocket;ws.binaryType="arraybuffer";ws.accept();return ws}
export async function duplexSocket(env){if(!env.VOLC_API_KEY)throw voiceError('全双工语音尚未配置',503);const headers={'X-Api-Key':env.VOLC_API_KEY};if(env.VOICE_CONNECT)return env.VOICE_CONNECT('wss://openspeech.bytedance.com/api/v3/duplex/realtime/dialogue',headers);const r=await fetch('https://openspeech.bytedance.com/api/v3/duplex/realtime/dialogue',{headers:{...headers,Upgrade:'websocket'}});if(!r.webSocket)throw voiceError(r.status===401||r.status===403?'全双工语音鉴权失败，请检查服务权限':'全双工语音连接失败，请稍后重试');const ws=r.webSocket;ws.accept();return ws}
function socketEvents(ws){const queued=[];let wake,ended=false;const push=x=>{queued.push(x);wake?.();wake=null};ws.addEventListener('message',e=>push({raw:e.data}));ws.addEventListener('error',()=>push({error:voiceError('语音连接中断，请重试')}));ws.addEventListener('close',()=>{ended=true;wake?.()});return {async next(){while(!queued.length&&!ended)await new Promise(r=>wake=r);if(queued.length){const e=queued.shift();if(e.error)throw e.error;return {value:await voiceDecode(e.raw),done:false}}return {done:true}},[Symbol.asyncIterator](){return this}}}
export function voiceB64(bytes){let s='';for(let p=0;p<bytes.length;p+=8192)s+=String.fromCharCode(...bytes.subarray(p,p+8192));return btoa(s)}
export async function* ttsAudio(env,text,voice,signal){const r=await (env.VOICE_FETCH||fetch)('https://openspeech.bytedance.com/api/v3/tts/unidirectional',{method:'POST',headers:{...voiceHeaders(env,'seed-tts-2.0'),'Content-Type':'application/json','X-Control-Require-Usage-Tokens-Return':'*'},body:JSON.stringify({user:{uid:'tinghai'},req_params:{text:spokenText(text),speaker:VOICES.some(v=>v.id===voice)?voice:VOICES[0].id,audio_params:{format:'mp3',sample_rate:24000},additions:JSON.stringify({context_texts:['请清楚、自然地讲解，注意句子之间的停顿。']})}}),signal});
 if(!r.ok){await r.body?.cancel();throw voiceError(r.status===401||r.status===403?'语音鉴权失败，请检查合成服务权限':'语音合成暂不可用（'+r.status+'）')}
 const reader=r.body.getReader(),decoder=new TextDecoder();let buffer='',finished=false,total=0;try{while(true){const {done,value}=await reader.read();buffer+=decoder.decode(value,{stream:!done});if(buffer.length>2e6)throw voiceError('语音数据超出限制');let n;while((n=buffer.indexOf('\n'))>=0||done&&buffer.trim()){const line=n>=0?buffer.slice(0,n):buffer;buffer=n>=0?buffer.slice(n+1):'';if(!line.trim())continue;const x=JSON.parse(line);if(x.code!==0&&x.code!==20000000)throw voiceError('语音合成失败，请检查音色权限与额度（'+x.code+'）');if(x.data){total+=x.data.length;if(total>16e6)throw voiceError('单段音频过长');yield {type:'audio',data:x.data}}if(x.code===20000000){finished=true;yield {type:'usage',usage:x.usage||{}}}}if(done)break}if(!finished||!total)throw voiceError('语音未完整生成，请重试')}finally{await reader.cancel().catch(()=>{});reader.releaseLock()}
}
export function splitVoiceSegments(segments){const out=[];segments.forEach((s,index)=>{const text=spokenText(s.text),sentences=text.match(/[^。！？；.!?]+[。！？；.!?]+|[^。！？；.!?]+$/g)||[];for(const sentence of sentences){let rest=sentence.trim();while(rest.length){let n=Math.min(280,rest.length);if(n<rest.length){const pause=Math.max(rest.lastIndexOf('，',n),rest.lastIndexOf(',',n),rest.lastIndexOf('、',n));if(pause>40)n=pause+1}out.push({...s,text:rest.slice(0,n),sourceIndex:index});rest=rest.slice(n)}}});if(!out.length||out.reduce((n,s)=>n+s.text.length,0)>10000)throw voiceError('播客讲稿需在 10000 字以内',400);return out}
export async function* podcastAudio(env,segments,signal,selectedVoices=podcastVoices){const ws=await voiceSocket(env,'/api/v3/sami/podcasttts','volc.service_type.10050'),events=socketEvents(ws),id=crypto.randomUUID();const end=()=>ws.close();signal?.addEventListener('abort',end,{once:true});const timer=setTimeout(end,180000);let finished=false,round=-1;try{ws.send(voiceFrame(100,{action:3,nlp_texts:segments.map(s=>({text:s.text,speaker:selectedVoices[s.speaker==='B'?1:0]})),use_head_music:false,use_tail_music:false,audio_config:{format:'mp3',sample_rate:24000},speaker_info:{random_order:false,speakers:selectedVoices}},id));for await(const m of events){if(m.type===15||m.event===153)throw voiceError('播客生成失败，请检查播客服务权限与额度（'+(m.code||m.data?.status_code||'服务错误')+'）');if(m.event===150)ws.send(voiceFrame(102,{},id));if(m.event===360){round++;yield {type:'round',index:round,text:m.data?.text||segments[round]?.text}}if(m.event===361)yield {type:'audio',index:round,data:voiceB64(m.body)};if(m.event===362){if(m.data?.is_error)throw voiceError('播客当前段生成失败');yield {type:'round-end',index:round,duration:m.data?.audio_duration,start:m.data?.start_time,end:m.data?.end_time}}if(m.event===154)yield {type:'usage',usage:m.data?.usage};if(m.event===152){finished=true;break}}if(!finished)throw voiceError('播客连接提前结束，可以重新生成')}finally{clearTimeout(timer);signal?.removeEventListener('abort',end);ws.close()}}
export function voiceStream(req,work){const controller=new AbortController();req.signal.addEventListener('abort',()=>controller.abort(),{once:true});const stream=new ReadableStream({async start(out){const send=d=>out.enqueue(voiceEncoder.encode('data: '+JSON.stringify(d)+'\n\n'));try{for await(const d of work(controller.signal))send(d);send({type:'complete'})}catch(e){try{send({type:'error',error:e.message||'语音服务暂不可用'})}catch{}}finally{try{out.close()}catch{}}},cancel(){controller.abort()}});return new Response(stream,{headers:{'Content-Type':'text/event-stream; charset=utf-8','Cache-Control':'no-store'}})}
function asrFrame(type,body,last=false){const data=body instanceof Uint8Array?body:voiceEncoder.encode(JSON.stringify(body));const a=new Uint8Array(8+data.length);a.set([0x11,(type<<4)|(last?2:0),type===1?0x10:0,0]);new DataView(a.buffer).setUint32(4,data.length);a.set(data,8);return a}
export async function runAsr(browser,env){let upstream,stopped=false,bytes=0,chain=Promise.resolve();const send=d=>{try{browser.send(JSON.stringify(d))}catch{}};const close=()=>{stopped=true;clearTimeout(timer);try{upstream?.close();browser.close()}catch{}};const timer=setTimeout(close,65000);browser.addEventListener('close',close);browser.addEventListener('error',close);try{upstream=await voiceSocket(env,'/api/v3/sauc/bigmodel_async','volc.seedasr.sauc.duration');if(stopped){upstream.close();return}const events=socketEvents(upstream);upstream.send(asrFrame(1,{user:{uid:'tinghai'},audio:{format:'pcm',codec:'raw',rate:16000,bits:16,channel:1},request:{model_name:'bigmodel',enable_itn:true,enable_punc:true,show_utterances:true,corpus:{context:JSON.stringify({hotwords:[{word:'听海'},{word:'知乎直答'}]})}}}));browser.addEventListener('message',e=>{if(stopped)return;try{if(typeof e.data==='string'){if(JSON.parse(e.data).type==='stop'){stopped=true;upstream.send(asrFrame(2,new Uint8Array(),true))}return}const a=new Uint8Array(e.data);bytes+=a.length;if(a.length>64000||bytes>1920000)throw Error();upstream.send(asrFrame(2,a))}catch{send({type:'error',error:'录音超出限制或格式无效'});close()}});send({type:'ready'});for await(const m of events){if(m.type===15)throw voiceError('语音识别失败，请检查识别服务权限与额度（'+m.code+'）');const result=m.data?.result;if(result?.text)send({type:'transcript',text:result.text,final:m.last});if(m.last){send({type:'done'});break}}}catch(e){send({type:'error',error:e.message||'语音识别暂不可用'})}finally{close()}}
export function asrUpgrade(req,env){if(req.headers.get('upgrade')?.toLowerCase()!=='websocket')throw voiceError('需要语音实时连接',400);voiceHeaders(env,'');if(env.ASR_UPGRADE)return env.ASR_UPGRADE(ws=>runAsr(ws,env));const pair=new WebSocketPair();pair[1].accept();runAsr(pair[1],env);return new Response(null,{status:101,webSocket:pair[0]})}
export async function transcribePcm(env,pcm,signal){
 let ws,timedOut=false;const close=()=>{try{ws?.close()}catch{}};
 const timer=setTimeout(()=>{timedOut=true;close()},25000);signal?.addEventListener('abort',close,{once:true});
 try{
  ws=await voiceSocket(env,'/api/v3/sauc/bigmodel_async','volc.seedasr.sauc.duration');
  if(signal?.aborted||timedOut)throw voiceError('语音识别已取消或超时',504);
  const events=socketEvents(ws);
  ws.send(asrFrame(1,{user:{uid:'tinghai'},audio:{format:'pcm',codec:'raw',rate:16000,bits:16,channel:1},request:{model_name:'bigmodel',enable_itn:true,enable_punc:true}}));
  for(let offset=0;offset<pcm.length;offset+=32000)ws.send(asrFrame(2,pcm.slice(offset,offset+32000),offset+32000>=pcm.length));
  let text='';for await(const m of events){if(m.type===15)throw voiceError('语音识别失败，请检查识别服务权限与额度（'+m.code+'）');if(m.data?.result?.text)text=m.data.result.text;if(m.last)return text.slice(0,400)}
  throw voiceError(timedOut?'语音识别超时，请重试':'语音识别连接提前结束，请重试',504);
 }finally{clearTimeout(timer);signal?.removeEventListener('abort',close);close()}
}
export function validateDuoVoices(voices){if(!Array.isArray(voices)||voices.length!==2||voices[0]===voices[1]||voices.some(id=>!VOICES.some(v=>v.id===id)))throw voiceError('请选择两位主持人的有效音色',400);return voices;}
export async function* episodeVoice(env,segments,style,voice,signal,duoVoices,clapperVoice){
 if(['first','story','clapper'].includes(style)){yield* clapperAudio(env,segments,signal,clapperVoice,style);return;}
 if(style==='duo'){yield* podcastAudio(env,segments,signal,duoVoices?validateDuoVoices(duoVoices):podcastVoices);return;}
 for(let i=0;i<segments.length;i++){if(signal.aborted)throw voiceError('生成已取消');yield {type:'round',index:i};const speaker=style==='duo'?VOICES[segments[i].speaker==='B'?1:0].id:voice;for await(const event of ttsAudio(env,segments[i].text,speaker,signal))yield {...event,index:i};yield {type:'round-end',index:i}}
}

export function splitPodcastSegments(segments){const out=[];segments.forEach((s,index)=>{let text=spokenText(s.text);while(text.length){let n=Math.min(300,text.length);if(n<text.length){const pause=Math.max(text.lastIndexOf('。',n-1),text.lastIndexOf('！',n-1),text.lastIndexOf('？',n-1),text.lastIndexOf('，',n-1));if(pause>0)n=pause+1;}out.push({...s,text:text.slice(0,n),sourceIndex:index});text=text.slice(n);}});if(!out.length||out.reduce((n,s)=>n+s.text.length,0)>10000)throw voiceError('播客讲稿需在10000字以内',400);return out;}
