const ORIGIN='https://developer.zhihu.com';
export const MODELS=['zhida-fast-1p5','zhida-thinking-1p5','zhida-agent'];
export class APIError extends Error{constructor(message,status=502,code='UPSTREAM_ERROR'){super(message);this.status=status;this.code=code}}
export function safeUrl(value){try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)&&!u.username&&!u.password?u.href:null}catch{return null}}
export function plain(value){return String(value??'').replace(/<[^>]*>/g,'').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&#39;/g,"'").replace(/&quot;/g,'"').trim()}
export function canonicalUrl(value){const v=safeUrl(value);if(!v)return null;const u=new URL(v);for(const k of [...u.searchParams.keys()])if(k.startsWith('utm_'))u.searchParams.delete(k);u.hash='';return u.href}
export function questionUrl(value){const v=safeUrl(value);if(!v)return null;const u=new URL(v);return /^(www\.)?zhihu\.com$/.test(u.hostname)&&/^\/question\/\d+\/?$/.test(u.pathname)?u.origin+u.pathname:null}
export function normalize(items,channel){return (items||[]).map(x=>({title:plain(x.DocName||x.Title||'知乎回答'),url:safeUrl(x.OriginUrl||x.Url),author:plain(x.AuthorName||x.Author?.Name||''),text:(Array.isArray(x.Content)?x.Content.map(plain).join('\n\n'):plain(x.ContentText||x.Summary||x.Abstract||'')),chunks:Array.isArray(x.Content)?x.Content.map(plain):undefined,channel,channels:[channel],kind:channel==='library'?'正文片段':'摘要',baseId:x.KnowledgeBaseID?String(x.KnowledgeBaseID):undefined,contentId:x.RecallContentID?String(x.RecallContentID):undefined,sourceHost:safeUrl(x.OriginUrl||x.Url)?new URL(safeUrl(x.OriginUrl||x.Url)).hostname:null})).filter(x=>x.text||x.title)}
export function dedupe(items){const out=[],seen=new Map();for(const x of items){const key=canonicalUrl(x.url)||`${x.baseId||''}:${x.contentId||''}:${x.title}`;if(seen.has(key)){const t=seen.get(key);t.channels=[...new Set([...t.channels,...x.channels])];if(x.text.length>t.text.length){t.text=x.text;t.chunks=x.chunks;t.kind=x.kind;}continue}const t={...x,text:x.text.slice(0,3500),chunks:x.chunks?.slice(0,3).map(c=>c.slice(0,2000)),id:'S'+(out.length+1)};seen.set(key,t);out.push(t);if(out.length>=12)break}return out}
export function citedIds(text,refs){const valid=new Set(refs.map(x=>x.id));return [...new Set([...String(text).matchAll(/\[(S\d+)\]/g)].map(m=>m[1]).filter(x=>valid.has(x)))]}
export function cleanCitations(text,refs){const valid=new Set(refs.map(x=>x.id));return String(text).replace(/\[(S\d+)\]/g,(m,id)=>valid.has(id)?m:'〔来源编号未核验〕')}
export function parseScript(text,refs,requestedStyle){let data;try{data=JSON.parse(text.trim().replace(/^```(?:json)?\s*/,'').replace(/\s*```$/,''))}catch{}const valid=new Set(refs.map(r=>r.id));if(Array.isArray(data?.segments)&&data.segments.length&&data.segments.length<=32){const segments=data.segments.filter(s=>typeof s.text==='string'&&s.text.trim()).map((s,i)=>({chapterTitle:typeof s.chapterTitle==='string'?plain(s.chapterTitle).trim().slice(0,12):'',speaker:requestedStyle==='duo'?(s.speaker==='B'?'B':'A'):'A',text:cleanCitations(plain(s.text).slice(0,1600),refs),sourceIds:Array.isArray(s.sourceIds)?s.sourceIds.filter(x=>valid.has(x)):citedIds(s.text,refs)}));if(segments.length)return {segments,style:requestedStyle,structured:true};}const segments=String(text).split(/\n\s*\n/).filter(x=>x.trim()).slice(0,20).map(x=>({speaker:'A',text:cleanCitations(plain(x).slice(0,1600),refs),sourceIds:citedIds(x,refs)}));return {segments,style:'solo',structured:false}}
function errorFor(status,code){if(status===401||status===403||code===20001)return new APIError('知乎凭据无效或该内容未获授权',403,'AUTH_REQUIRED');if(status===429||[30001,30002,30003].includes(code))return new APIError('知乎接口额度、频率或风控限制，请稍后再试',429,'RATE_LIMITED');if(code===10001)return new APIError('知乎接口参数不被接受，请调整查询',400,'INVALID_ARGUMENT');if(code===40004)return new APIError('知识库不存在或不可访问',404,'NOT_FOUND');if(code===40005)return new APIError('文件仍在处理中，请先查看知识库内容，不要重复上传',409,'PROCESSING');return new APIError('知乎服务暂时无法完成请求',502,'UPSTREAM_ERROR')}
function deadline(parent,timeout){const controller=new AbortController(),onAbort=()=>controller.abort(parent?.reason),timer=setTimeout(()=>controller.abort(),timeout);if(parent){if(parent.aborted)onAbort();else parent.addEventListener('abort',onAbort,{once:true})}return {signal:controller.signal,dispose(){clearTimeout(timer);parent?.removeEventListener('abort',onAbort)}}}
function logFetchError(path,error){console.error('zhihu_fetch_failed',JSON.stringify({path,name:error?.name||'Error',message:String(error?.message||error).slice(0,240)}))}
export class Zhihu{constructor(secret,fetcher=fetch,oauthToken=''){this.secret=secret;this.fetcher=fetcher.bind(globalThis);this.oauthToken=oauthToken}headers(){if(!this.secret)throw new APIError('尚未配置知乎接入凭据',503,'NOT_CONFIGURED');return {Authorization:`Bearer ${this.secret}`,...(this.oauthToken?{'X-OAuth-Token':this.oauthToken}:{}),'X-Request-Timestamp':String(Math.floor(Date.now()/1000)),'Content-Type':'application/json'}}async request(path,{body,signal,timeout=25000,method}={}){let res;const limit=deadline(signal,timeout);try{res=await this.fetcher(ORIGIN+path,{method:method||(body?'POST':'GET'),headers:this.headers(),body:body?JSON.stringify(body):undefined,signal:limit.signal});}catch(e){if(e instanceof APIError)throw e;logFetchError(path,e);throw new APIError('知乎请求超时或网络暂不可用；未自动重试',504,'TIMEOUT')}finally{limit.dispose()}let data;try{data=await res.json()}catch{throw new APIError('知乎返回了无法解析的响应',502,'INVALID_RESPONSE')}if(!res.ok||data.error||(data.Code!==undefined&&data.Code!==0))throw errorFor(res.status,data.Code);return data.Data??data}
 async search(channel,query,options={}){if(channel==='library')return this.request('/api/v1/knowledge/search',{body:{Query:query,RecallScopes:options.scopes||['public'],...(options.baseIds?.length?{KnowledgeBaseIDs:options.baseIds}:{}),Limit:3}});return this.request('/api/v1/content/'+(channel==='web'?'global_search':'zhihu_search')+'?'+new URLSearchParams({Query:query,Count:'4'}))}
 async completion(model,prompt,{signal}={}){const d=await this.request('/v1/chat/completions',{body:{model,messages:[{role:'user',content:prompt}],stream:false},timeout:140000,signal});const text=d.choices?.[0]?.message?.content;if(typeof text!=='string'||!text.trim())throw new APIError('知乎直答没有返回可显示的回答',502,'EMPTY_ANSWER');return text}
 async *stream(model,prompt,signal){let res;const limit=deadline(signal,140000);try{try{res=await this.fetcher(ORIGIN+'/v1/chat/completions',{method:'POST',headers:this.headers(),body:JSON.stringify({model,messages:[{role:'user',content:prompt}],stream:true}),signal:limit.signal})}catch(e){logFetchError('/v1/chat/completions',e);throw new APIError('知乎直答暂时无法连接',504,'TIMEOUT')}if(!res.ok){let d={};try{d=await res.json()}catch{}throw errorFor(res.status,d.Code)}if(!res.headers.get('content-type')?.includes('text/event-stream')){const d=await res.json();if(d.error||d.Code)throw errorFor(res.status,d.Code);const t=d.choices?.[0]?.message?.content;if(!t)throw new APIError('知乎直答没有返回正文');yield t;return}const reader=res.body.getReader(),decoder=new TextDecoder();let buffer='',doneMarker=false;try{while(true){const {done,value}=await reader.read();buffer+=decoder.decode(value,{stream:!done});let n;while((n=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,n).trim();buffer=buffer.slice(n+1);if(!line.startsWith('data:'))continue;const raw=line.slice(5).trim();if(raw==='[DONE]'){doneMarker=true;break}if(!raw)continue;let event;try{event=JSON.parse(raw)}catch{throw new APIError('直答流数据不完整',502,'INVALID_RESPONSE')}if(event.error||event.choices?.[0]?.finish_reason==='error')throw new APIError('直答在生成途中失败，已保留检索材料',502,'STREAM_ERROR');const t=event.choices?.[0]?.delta?.content;if(t)yield t;}if(doneMarker||done)break;}if(!doneMarker)throw new APIError('直答连接提前结束，回答可能不完整',502,'STREAM_INCOMPLETE')}finally{await reader.cancel().catch(()=>{});reader.releaseLock()}}catch(e){if(limit.signal.aborted&&!signal?.aborted)throw new APIError('知乎直答整理超时，来源已保留，请稍后重试',504,'TIMEOUT');throw e}finally{limit.dispose()}}
 async upload(form,signal){const h=this.headers();delete h['Content-Type'];const limit=deadline(signal,200000);try{let r;try{r=await this.fetcher(ORIGIN+'/api/v1/knowledge/files',{method:'POST',headers:h,body:form,signal:limit.signal})}catch(e){logFetchError('/api/v1/knowledge/files',e);throw new APIError('知乎请求超时或网络暂不可用；未自动重试',504,'TIMEOUT')}const d=await r.json();if(!r.ok||d.Code!==0)throw errorFor(r.status,d.Code);return d.Data}finally{limit.dispose()}}}
