import fs from 'node:fs';
import path from 'node:path';
import {AsyncLocalStorage} from 'node:async_hooks';
export const traces=new AsyncLocalStorage();
const root=path.resolve('log');
const privateKey=/authorization|cookie|secret|api.?key|token|^context$|password/i;
export function sanitize(value,key=''){
 if(privateKey.test(key))return '[REDACTED]';
 if(Buffer.isBuffer(value)||value instanceof ArrayBuffer||ArrayBuffer.isView(value))return {binaryBytes:value.byteLength};
 if(typeof value==='string'){let s=value.replace(/[A-Za-z0-9_-]{180,}\.[A-Za-z0-9_-]{35,}/g,'[SIGNED_CONTEXT_REDACTED]');for(const secret of [process.env.VOLC_API_KEY,process.env.ZHIHU_ACCESS_SECRET])if(secret)s=s.replaceAll(secret,'[REDACTED]');return s.length>65536?{text:s.slice(0,65536),truncated:true,totalChars:s.length}:s}
 if(Array.isArray(value))return value.map(x=>sanitize(x));
 if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,(k==='audio'||k==='audio_data'||k==='data'||k==='delta')&&typeof v==='string'&&v.length>256&&/^[A-Za-z0-9+/=]+$/.test(v)?{base64Bytes:Math.floor(v.length*3/4)}:sanitize(v,k)]));return value;
}
export function logEvent(event){try{fs.mkdirSync(root,{recursive:true});const row=sanitize({time:new Date().toISOString(),traceId:traces.getStore()?.traceId||null,model:null,input:null,output:null,...event});const date=row.time.slice(0,10);for(const ext of ['jsonl','log']){let target=path.join(root,`${date}.${ext}`);if(fs.existsSync(target)&&fs.statSync(target).size>10*1024*1024)fs.renameSync(target,path.join(root,`${date}-${Date.now()}-${crypto.randomUUID().slice(0,6)}.${ext}`));fs.appendFileSync(target,ext==='jsonl'?JSON.stringify(row)+'\n':`[${row.time}] ${row.phase||''} ${row.kind||''} trace=${row.traceId} call=${row.callId||''}\n${JSON.stringify(row,null,2)}\n`)}}catch(e){console.error('API_LOG_WRITE_FAILED',e.message)}}
export function collector(type=''){let size=0,text='',buffer='',events=[];const decoder=new TextDecoder();return {push(chunk){const bytes=typeof chunk==='string'?Buffer.from(chunk):new Uint8Array(chunk);size+=bytes.length;if(!/json|text|event-stream/i.test(type))return;if(/event-stream|ndjson/i.test(type)){buffer+=decoder.decode(bytes,{stream:true});let i;while((i=buffer.indexOf('\n'))>=0){let line=buffer.slice(0,i).trim();buffer=buffer.slice(i+1);if(line.startsWith('data:'))line=line.slice(5).trim();if(!line)continue;try{events.push(sanitize(JSON.parse(line)))}catch{events.push(sanitize(line))}if(events.length>2000)events.shift()}if(buffer.length>262144)buffer=buffer.slice(-262144)}else if(text.length<33554432)text+=decoder.decode(bytes,{stream:true})},result(){if(events.length)return {bytes:size,events,lastPartial:sanitize(buffer)};if(!/json|text|event-stream/i.test(type))return {binaryBytes:size};try{return sanitize(JSON.parse(text))}catch{return {bytes:size,text:/"audio"\s*:/.test(text)?'[AUDIO_RESPONSE_TRUNCATED]':sanitize(text),truncated:size>33554432}}}}}
export async function loggedFetch(url,init={}){const callId=crypto.randomUUID(),started=Date.now(),traceId=traces.getStore()?.traceId;let input=init.body;try{input=JSON.parse(input)}catch{if(input instanceof FormData)input=Object.fromEntries([...input].map(([k,v])=>[k,typeof v==='string'?v:{name:v.name,size:v.size,type:v.type}]))}const model=input?.model||input?.req_params?.speaker||null;logEvent({kind:'upstream.http',phase:'start',callId,url:String(url),method:init.method||'GET',model,input});try{const response=await fetch(url,init);const capture=collector(response.headers.get('content-type')||'');let ended=false;const finish=(extra={})=>{if(ended)return;ended=true;logEvent({kind:'upstream.http',phase:'end',traceId,callId,url:String(url),model,status:response.status,durationMs:Date.now()-started,output:capture.result(),...extra})};if(!response.body){finish();return response}const reader=response.body.getReader();return new Response(new ReadableStream({async pull(out){try{const {done,value}=await reader.read();if(done){finish();out.close()}else{capture.push(value);out.enqueue(value)}}catch(e){finish({error:e.message});out.error(e)}},async cancel(reason){finish({canceled:true});await reader.cancel(reason)}}),{status:response.status,statusText:response.statusText,headers:response.headers})}catch(e){logEvent({kind:'upstream.http',phase:'error',traceId,callId,model,url:String(url),durationMs:Date.now()-started,error:e.message});throw e}}
export function traceHttp(req,res,work){const traceId=crypto.randomUUID();return traces.run({traceId},()=>{const start=Date.now(),input=collector(req.headers['content-type']||'');let output=collector('application/json');const head=res.writeHead;res.writeHead=function(status,...args){const h=args.at(-1);if(h&&typeof h==='object')output=collector(h['content-type']||h['Content-Type']||res.getHeader('Content-Type')||'application/json');else output=collector(res.getHeader('Content-Type')||'application/json');return head.call(this,status,...args)};const emit=req.emit;req.emit=function(name,...args){if(name==='data')input.push(args[0]);return emit.call(this,name,...args)};const write=res.write,end=res.end;res.write=function(chunk,...args){if(chunk)output.push(chunk);return write.call(this,chunk,...args)};res.end=function(chunk,...args){if(chunk&&typeof chunk!=='function')output.push(chunk);return end.call(this,chunk,...args)};let done=false;const finish=()=>{if(done)return;done=true;logEvent({traceId,callId:traceId,kind:'local.http',phase:'end',url:req.url,method:req.method,input:input.result(),output:output.result(),status:res.statusCode,durationMs:Date.now()-start,aborted:!res.writableFinished})};res.setHeader('X-Trace-Id',traceId);res.on('finish',finish);res.on('close',finish);logEvent({kind:'local.http',phase:'start',callId:traceId,url:req.url,method:req.method});return work()})}
export function traceSocket(ws,{kind='upstream.ws',url,traceId=traces.getStore()?.traceId}={}){const callId=crypto.randomUUID(),started=Date.now();let model=null,inBytes=0,outBytes=0;const record=(phase,details)=>logEvent({traceId,callId,kind,url,phase,model,...details});const parse=x=>{try{return JSON.parse(typeof x==='string'?x:Buffer.from(x).toString())}catch{return null}};record('open',{});const send=ws.send;ws.send=function(data,...args){const m=parse(data);if(m){model=m.session?.model||m.model||model;if(m.type==='input_audio_buffer.append')inBytes+=Buffer.from(m.audio||'','base64').length;else if(m.type==='audio')inBytes+=Buffer.from(m.data||'','base64').length;else record('send',{input:m})}else inBytes+=data.byteLength||data.length||0;return send.call(this,data,...args)};ws.on('message',(data,binary)=>{const m=parse(data);if(m){if(m.type==='response.output_audio.delta')outBytes+=Buffer.from(m.delta||'','base64').length;else record('receive',{output:m})}else{outBytes+=data.byteLength||data.length||0}});ws.on('error',e=>record('error',{error:e.message}));ws.on('close',(code)=>record('end',{code,durationMs:Date.now()-started,input:{audioBytes:inBytes},output:{audioBytes:outBytes}}));return ws}
