import {localLibrary} from './local-library.mjs';
import {localCatalog} from './local-catalog.mjs';
import {localShare} from './local-share.mjs';
import {traceHttp,traces,logEvent,loggedFetch,traceSocket} from './api-log.mjs';
import {diagnosticConnect,recordVoice} from './local-voice-log.mjs';
import {localCache} from './local-cache.mjs';
import {WebSocketServer} from 'ws';import {nodeVoiceConnect} from './voice-node.mjs';
import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import {Readable} from 'node:stream';import {api} from '../server/app.mjs';
try{process.loadEnvFile('.env.local')}catch{}
const voiceEnv={VOLC_API_KEY:process.env.VOLC_API_KEY,ZHIHU_OAUTH_APP_ID:process.env.ZHIHU_OAUTH_APP_ID,ZHIHU_OAUTH_APP_KEY:process.env.ZHIHU_OAUTH_APP_KEY,ZHIHU_OAUTH_REDIRECT_URI:process.env.ZHIHU_OAUTH_REDIRECT_URI,VOICE_CONNECT:diagnosticConnect,FETCH:loggedFetch,VOICE_FETCH:loggedFetch};
const root=path.resolve('public');const server=http.createServer(async(req,res)=>{if(req.url.startsWith('/api/')||req.url.startsWith('/auth/')||req.url.startsWith('/__local/'))return traceHttp(req,res,()=>handle(req,res));return handle(req,res)});async function handle(req,res){if(await localCatalog(req,res))return;if(await localShare(req,res))return;if(await localLibrary(req,res))return;if(await localCache(req,res))return;const controller=new AbortController();res.on('close',()=>{if(!res.writableEnded)controller.abort()});try{const url='http://127.0.0.1:4173'+req.url;let response;if(new URL(url).pathname.startsWith('/api/')||new URL(url).pathname.startsWith('/auth/')){const headers=new Headers();for(const [k,v]of Object.entries(req.headers))if(v)headers.set(k,String(v));const r=new Request(url,{method:req.method,headers,...(!['GET','HEAD'].includes(req.method)?{body:Readable.toWeb(req),duplex:'half'}:{}),signal:controller.signal});response=await api(r,{...voiceEnv,ZHIHU_ACCESS_SECRET:process.env.ZHIHU_ACCESS_SECRET,LOCAL_DEV:true});}else{let route=decodeURIComponent(new URL(url).pathname);const file=path.resolve(root,'.'+(route==='/'?'/index.html':route));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404).end('Not found');return}response=new Response(path.basename(file)==='index.html'?fs.readFileSync(file,'utf8').replace('</body>','<script>'+fs.readFileSync(new URL('./local-cache-client.js',import.meta.url),'utf8')+'</script></body>'):fs.readFileSync(file),{headers:{'Content-Type':({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.mp3':'audio/mpeg','.jpg':'image/jpeg','.png':'image/png','.webp':'image/webp','.svg':'image/svg+xml'})[path.extname(file)]||'application/octet-stream'}})}res.writeHead(response.status,Object.fromEntries(response.headers));if(response.body){Readable.fromWeb(response.body).pipe(res)}else res.end();}catch{if(!res.headersSent)res.writeHead(500);res.end('Service unavailable')}}server.listen(4173,'127.0.0.1',()=>console.log('Local: http://127.0.0.1:4173'));process.on('SIGINT',()=>server.close(()=>process.exit(0)));

const voiceWss=new WebSocketServer({noServer:true});server.on("upgrade",async(req,socket,head)=>traces.run({traceId:crypto.randomUUID()},async()=>{logEvent({kind:"browser.ws",phase:"upgrade",url:req.url});const headers=new Headers();for(const [k,v]of Object.entries(req.headers))if(v)headers.set(k,String(v));const upgrade=callback=>{voiceWss.handleUpgrade(req,socket,head,ws=>{ws.binaryType="arraybuffer";traceSocket(ws,{kind:"browser.ws",url:req.url});callback(ws)});return new Response(null)};const result=await api(new Request("http://127.0.0.1:4173"+req.url,{headers}),{...voiceEnv,ZHIHU_ACCESS_SECRET:process.env.ZHIHU_ACCESS_SECRET,LOCAL_DEV:true,ASR_UPGRADE:upgrade,DUPLEX_UPGRADE:upgrade});if(result.status!==200){logEvent({kind:"browser.ws",phase:"rejected",status:result.status,url:req.url});recordVoice('浏览器升级被拒绝',{status:result.status,detail:await result.text()});socket.end("HTTP/1.1 "+result.status+" Error\r\nConnection: close\r\n\r\n")}}));
