import {voiceLog} from './local-voice-log.mjs';
import fs from 'node:fs/promises';
import {seal,unseal} from '../server/app.mjs';
import {ttsAudio,VOICES} from '../server/voice.mjs';
const dir=new URL('../.local-cache/',import.meta.url);
const file=name=>new URL(name+'.json',dir);
const secret=()=>process.env.ZHIHU_ACCESS_SECRET;
async function read(name){try{return JSON.parse(await fs.readFile(file(name),'utf8'))}catch(e){if(e.code==='ENOENT')return null;throw e}}
async function write(name,data){await fs.mkdir(dir,{recursive:true});await fs.writeFile(file(name+'-pending'),JSON.stringify(data));await fs.rename(file(name+'-pending'),file(name))}
export async function seedDemo(){if(await read('demo'))return;const segments=[{speaker:'A',sourceIds:[],text:'欢迎来到听海的本地测试节目。天空看起来是蓝色的，是因为太阳光经过大气时，较短波长的蓝光比红光更容易被散射。你可以现在按住问一句，试试询问为什么日落时天空会变红。'},{speaker:'A',sourceIds:[],text:'日落时，阳光穿过的大气路径更长。许多蓝光已经被散射到其他方向，进入我们眼睛的直射光就显得偏红。这是一段预置测试讲稿，没有经过本次知乎检索，主要用来反复验证播放、暂停和语音插话。'}];const ctx={query:'本地测试：天空与日落',channels:['zhihu'],scopes:['public'],baseIds:[],references:[],status:[],script:segments,style:'solo'};const audio=[];for(const s of segments){const chunks=[];for await(const e of ttsAudio({VOLC_API_KEY:process.env.VOLC_API_KEY},s.text,VOICES[0].id,new AbortController().signal))if(e.type==='audio')chunks.push(Buffer.from(e.data,'base64'));audio.push({data:Buffer.concat(chunks).toString('base64')})}await write('demo',{ctx,episode:{title:ctx.query,style:'solo',segments,references:[],citedIds:[],audio,audioStatus:'ready',engine:'tts',audioNote:'预置测试讲稿 · 未进行知乎检索'},savedAt:new Date().toISOString()})}
export async function localCache(req,res){const url=new URL(req.url,'http://127.0.0.1:4173');if(!url.pathname.startsWith('/__local/'))return false;const origin='http://'+req.headers.host;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');const send=(data,status=200)=>{res.writeHead(status);res.end(JSON.stringify(data))};if(!['127.0.0.1:4173','localhost:4173'].includes(req.headers.host)||req.headers.origin&&req.headers.origin!==origin){send({error:'仅允许本机同源请求'},403);return true}try{if(url.pathname==='/__local/voice-log'){send({events:voiceLog.filter(e=>e.service==='duplex'||e.stage==='浏览器升级被拒绝')});return true}const name=url.pathname==='/__local/demo'?'demo':'latest';if(req.method==='GET'){const cached=await read(name);if(!cached){send({available:false});return true}if(url.searchParams.has('summary')){send({available:true,title:cached.episode.title,savedAt:cached.savedAt});return true}const context=await seal(cached.ctx,secret(),'local-preview');send({available:true,episode:{...cached.episode,context}})}else if(req.method==='POST'&&name==='latest'){let bytes=0,parts=[];for await(const part of req){bytes+=part.length;if(bytes>32e6)throw Error('缓存超过 32 MB 上限');parts.push(part)}const ep=JSON.parse(Buffer.concat(parts));const ctx=await unseal(ep.context,secret(),'local-preview');if(!ep.audio?.length||ep.audio.length!==ep.segments?.length||ep.audio.some(a=>!a.data||!/^[A-Za-z0-9+/=]+$/.test(a.data)))throw Error('仅缓存已完整生成的节目');await write('latest',{ctx,episode:ep,savedAt:new Date().toISOString()});send({saved:true})}else send({error:'不支持此操作'},405)}catch(e){send({error:e.message},400)}return true}
